# Generated by Django 4.1.10 on 2024-01-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxdj', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
